server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

ping:
  resourceServerUrl: http://localhost:8000
  environmentId: <environment_id>

spring:
  security:
    oauth2:
      client:
        registration:
          pingidentity:
            client-id: <authorization_code_client_id>
            client-secret: <authorization_code_client_client_credentials_client_secret>
            provider: pingidentity
            scope: openid,message
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          pingidentity:
            issuer-uri: https://auth.pingone.com/<environment_id>/as/
